stages:
    - build
    - test
    - omg

cache:
    paths:
        - .build-ids/
        - .test-branch

.build-module: &build_definition
    stage: build
    tags:
        - bits
        - docker
    script:
        - /opt/bits-tools/build-tools/package-module.py -a '/usr/bin/destiny -d ./' -m ./ --version "${CI_COMMIT_TAG}"

build-rc:
  <<: *build_definition
  only:
    - /^[0-9]*\.[0-9]*\.[0-9]*-rc\.[0-9]*$/
  except:
    - branches
  artifacts:
    paths:
      - "*.tgz"
    expire_in: 10d

build-release:
  <<: *build_definition
  only:
    - /^[0-9]*\.[0-9]*\.[0-9]*$/
  except:
    - branches
  artifacts:
    paths:
      - "*.tgz"

build-master:
  <<: *build_definition
  only:
    - master
  except:
    - tags
  artifacts:
    paths:
      - "*.tgz"

build-branch:
  <<: *build_definition
  except:
    - master
    - tags
  artifacts:
    paths:
      - "*.tgz"
    expire_in: 3d
